beautiful-atoms/beautiful-atoms

.github/workflows/batoms_plugin_test.yaml

#6 Fix Lint workflow to exclude file use Blender custom python class

Add exclude to flake8, fix issue with Blener built-in python class

---

.github/workflows/build_blender_env_image.yml
.github/workflows/build_main_image.yml

Only support Blender 3.0.0 or newer.

remove blender 2.93

---

.github/workflows/batoms_plugin_test.yaml

Save user pref for addons

---

batoms/bond/__init__.py
batoms/bond/bondsetting.py

Add a new bond style: 3, to represent the bond by a spiral.
``` python
co2.bonds[0].style = 3
co2.bonds[1].style = 3
```

add feature: spiral bond

---

batoms/__init__.py
batoms/batoms.py
batoms/ops/add_surface.py
batoms/utils/butils.py

Automatically load all batoms into the python console.

auto load Batoms in python console

---

batoms/ops/add_object.py

"replace . by _ in the name"

---

README.md

previous README badge link was to my forked repo. updated

fix repo name in badge

---

Dockerfiles/Dockerfile.base_3.x
Dockerfiles/Dockerfile.main

Fix permission bug in main container image

---

.github/workflows/test_install_script.yaml
install.py

Update install script with --develop and --no-mamba switches

---

.github/workflows/test_install_script.yaml
install.py

Improvements for `install.py`:
- Implemented versioned installation with `-t` option
- Allow versioned install without specifying local repo path
- Color output for ANSI compatible terminal

Enhance `install.py`

---

batoms/bspecies.py
tests/test_batoms.py
tests/test_species.py

#149 
Now the color setter and `species.update()` work.

Fix bug for species

---

batoms/bond/bond.py
batoms/bond/search_bond.py
batoms/boundary.py
batoms/cell.py
batoms/draw/__init__.py
batoms/internal_data/bpy_data.py
tests/test_cell.py

1) fix bug: do not pop default_bond_data
2) use self.obj as the parent of the offsets object

fix bug: empty bond

---

batoms/base/object.py
batoms/batoms.py
batoms/plugins/cavity/bpy_data.py
batoms/plugins/cavity/cavity.py
tests/test_cavity.py
tests/test_preference.py

Support set:
- the minimum radius of the cavity to be searched.
- the resolution was used to build the meshgrid for searching cavity.

support setting minCave and resolution for Cavity

---

.gitignore
batoms/asset/asset.py
batoms/base/collection.py
batoms/base/object.py
batoms/batoms.py
batoms/bond/setting.py
batoms/bspecies.py
batoms/preferences.py
batoms/render/render.py
batoms/utils/butils.py

#166 
Add some functions to help build the asset library for Batoms.

Asset library

---

batoms/gui/__init__.py
batoms/gui/gui_volumetric_data.py
batoms/internal_data/bpy_data.py
batoms/ops/__init__.py
batoms/ops/ops_volumetric_data.py
batoms/plugins/isosurface/bpy_data.py
batoms/plugins/isosurface/isosurface.py
batoms/plugins/isosurface/ui_list.py
batoms/plugins/molecular_surface/molecular_surface.py
tests/test_isosurface.py
tests/test_volumetric_data.py

Enhancement
---------------------------
Update panel to support creating new volumetric data by adding or subtracting old volumetric data. Application: Maps of electron density difference
Fix bug
------------------
- update isosurface using `colored_by_attribute`.

Update volumetric data

---

.github/workflows/batoms_plugin_test.yaml
.github/workflows/build_blender_env_image.yml
.github/workflows/build_main_image.yml
batoms/base/object.py
batoms/batoms.py
batoms/bond/bond.py
batoms/bond/search_bond.py
batoms/boundary.py
batoms/cell.py
batoms/console.py
batoms/internal_data/bpy_data.py
batoms/plugins/cavity/cavity.py
batoms/plugins/highlight/highlight.py
batoms/polyhedra/polyhedra.py

This PR supports Blender version > 3.4. There are several [updates](https://github.com/beautiful-atoms/beautiful-atoms/wiki/Blender-3.4-update) for Blender 3.4. 
@alchem0x2A  Some important updates.
- `!!! This PR does not support the old Blender versions (<3.4). Thus after this PR is merged, the main branch will not support Blender <3.4 too`. Because if we want to support versions >= 3.4 and < 3.4, there will be a lot of ``if .. else ..`` to check the version, making the code very hard to read and maintain. 
- I duplicate the current `main` branch to a new branch, `blender-3.2`. People who want to use Blender <=3.2 can download batoms from this branch.
- Therefore, for the GitHub workflow, we will only test the version >=3.4.

Blender 3.4

---

batoms/base/object.py
batoms/internal_data/bpy_data.py

The order to save the data is corrected.

fix set and get attribute

---

README.md
batoms/database/mp.py
batoms/database/pymatgen.py
batoms/gui/gui_io.py
install.py
tests/test_database.py

Use the new MP API

---

batoms/batoms.py
batoms/bspecies.py

update the geometry node input with new material

---

batoms/batoms.py
batoms/bond/bond.py
batoms/bond/search_bond.py
batoms/boundary.py
batoms/cell.py
batoms/plugins/highlight/highlight.py
batoms/polyhedra/polyhedra.py

- GeometryNodeSampleIndex
- ShaderNodeVectorMath

The following nodes update their input and output sockets.

---

batoms/base/object.py
batoms/batoms.py
batoms/bond/bond.py
batoms/bond/search_bond.py
batoms/bond/setting.py
batoms/boundary.py
batoms/cell.py
batoms/plugins/cavity/cavity.py
batoms/plugins/highlight/highlight.py
batoms/polyhedra/polyhedra.py
batoms/utils/butils.py
batoms/utils/utils_node.py
tests/test_node_group.py

Add `get_cell_node` function to get the cell matrix node, it has three outputs:
-  Matrix
- Transpose
- Invert: invert of the cell matrix.
Add `get_projected_position` function to:
- Get scaled positions
- Get cartesian positions
The Project Point node projects a vector is used for the transformation.

use `Matrix` node

---

batoms/base/object.py
batoms/batoms.py
batoms/bond/bond.py
batoms/bond/gui.py
batoms/bond/search_bond.py
batoms/bond/setting.py
batoms/boundary.py
batoms/cell.py
batoms/gui/gui_volumetric_data.py
batoms/gui/ui_list_species.py
batoms/plugins/cavity/cavity.py
batoms/plugins/cavity/gui.py
batoms/plugins/crystal_shape/gui.py
batoms/plugins/highlight/gui.py
batoms/plugins/highlight/highlight.py
batoms/plugins/isosurface/ui_list.py
batoms/plugins/lattice_plane/gui.py
batoms/plugins/magres/ui_list.py
batoms/plugins/molecular_surface/ui_list.py
batoms/plugins/template/gui.py
batoms/polyhedra/polyhedra.py
batoms/polyhedra/ui_list.py
batoms/render/bpy_data.py
batoms/render/render.py
batoms/utils/attribute.py
batoms/utils/butils.py
batoms/utils/utils_node.py
tests/test_batoms.py
tests/test_node_group.py

Update geometry node to support Blender >=4.2

Support Blender 4.2
